# Generated by Django 6.0.1 on 2026-01-28 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100, verbose_name='Markė')),
                ('model', models.CharField(max_length=100, verbose_name='Modelis')),
                ('license_plate', models.CharField(max_length=20, verbose_name='Valstybinis Numeris')),
                ('vin_code', models.CharField(max_length=17, unique=True, verbose_name='VIN Code')),
                ('client_name', models.CharField(max_length=100, verbose_name='Kliento Vardas')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Paslauga')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kaina')),
            ],
            options={
                'verbose_name': 'Paslauga',
                'verbose_name_plural': 'Paslaugos',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.car', verbose_name='Automobilis')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Kiekis')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservice.order', verbose_name='Užsakymas')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.service', verbose_name='Paslauga')),
            ],
        ),
    ]
